### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by janpio** [MaxToyberman/fastlane-plugin-upload-to-server#6]
I come from https://github.com/fastlane/fastlane/pull/13893, a few questions:
- Does this always use the name `file` for the uploaded file?
- `multipartPayload` are just additional form values one can set?
- I currently have something like this:
```
require 'net/http/post/multipart'
    
        url = URI.parse('endpoint')
        File.open(filename) do |file|
          req = Net::HTTP::Post::Multipart.new url.path,
            "datei" => UploadIO.new(file, "application/zip", filename)
          res = Net::HTTP.start(url.host, url.port) do |http|
            return http.request(req).body
          end
        end
```
Could this be replaced with your plugin?

**Comment by MaxToyberman** [comment]
@janpio currenty it is possible to upload only ipa and apk's ,though it is not a problem to add this option

1) Does this always use the name file for the uploaded file -  yes, it must be file
2)multipartPayload are just additional form values one can set? , yes - you can set anything

**Comment by MaxToyberman** [comment]
@janpio  look at this branch i have created just now, `upload_custom_file`  use it and try something like this.
```

  desc "Submit a new file to my server"
  lane :uploadToServer do |options|
    upload_to_server(
      endPoint: 'https://yourdomain.com/api/UploadFiles',
      file: 'your file path',
   headers: {
        :content-type => "application/zip"
    },
      multipartPayload: {
        : filename => 'appName'
      }
    )

  end
```

**Comment by janpio** [comment]
Ok, now it would only be missing an option to define the file "param" (`file` vs. `datei`).

**Comment by Cyberuben** [comment]
I'm looking for this functionality as well.

Wouldn't it be as simple as defining a variable key in the params? My knowledge of Ruby isn't great, so not asking the obvious.

**Comment by MaxToyberman** [comment]
version 1.0.3 uploaded, includes file upload support @Cyberuben  @janpio

**Comment by Cyberuben** [comment]
I think you misunderstood what we meant.

Right now, the file uploaded to the server (doesn't matter if that's an IPA, APK or custom file), it is uploaded with the form field `file`. I have an upload endpoint that expects a form field `apk` or `ipa`. I can't change that using your module.

Could you please update your module to allow for a variable form field name?

**Comment by MaxToyberman** [comment]
@Cyberuben ok, no problem

**Comment by MaxToyberman** [comment]
@Cyberuben  @janpio  a new version was release 0.1.5 that support your request. 
just add
        :fileFormFieldName => 'your field name ',
in multipartPayload.

**Comment by mdNazmulHasan** [comment]
how to convert this , `curl -X POST -u <api-key>: https://cloud.bitbar.com/api/me/files -F "file=@BitbarSampleApp.apk"` in fastlane using this plugin ? @MaxToyberman

**Comment by tyndria** [comment]
@mdNazmulHasan were you able to upload files to bitbar eventually? :)

**Comment by mdNazmulHasan** [comment]
@tyndria I was able to eventually .

**Comment by tyndria** [comment]
@mdNazmulHasan maybe you could share somehow?

**Comment by mdNazmulHasan** [comment]
Sorry, currently I don't remember exactly how I did it. Also don't have the code with me  anymore. But, remember just a gist of it. It was probably depending on how the bearer token was passed with the upload script. I think i manually copied the bearer token from the postman request and added in the script. @tyndria
